Tracy: Camera Class Reference
Camera Class Reference
Represents the camera and determines the point from which rays are cast in the scene.
#include <camera.h>
Public Member Functions
Camera ()
void setOrigin (double[3])
void setUp (double[3])
Defines the up vector used by the camera, usually set to +Y.
void setRight (double[3])
Defines the right vector used by the camera.
void setForward (double[3])
Defines the forward vector used by the camera.
void setFocus (double[3])
Computes up/right/forward vectors so that we are focusing on given point.
void getPixelRay (double x, double y, double origin[3], double direction[3])
Assigns the origin/direction ray corresponding to a given pixel where x/y is a fraction 0.0 - 1.0 of screen width/height.
Private Attributes
double origin [3]
double up [3]
double right [3]
double forward [3]
double tanFovY
double tanFovX
Detailed Description
Represents the camera and determines the point from which rays are cast in the scene.
Use this to modify the perspective and to move the camera between frames.
Definition at line 32 of file camera.h.
Constructor & Destructor Documentation
Camera::Camera ()
Definition at line 28 of file camera.cc.
References forward, origin, right, tanFovX, tanFovY, up, and zero().
Member Function Documentation
void Camera::getPixelRay (double x, double y, double origin[3], double direction[3])
Assigns the origin/direction ray corresponding to a given pixel where x/y is a fraction 0.0 - 1.0 of screen width/height.
Definition at line 57 of file camera.cc.
References assign(), forward, normalize(), right, tanFovX, tanFovY, and up.
void Camera::setFocus (double focus[3])
Computes up/right/forward vectors so that we are focusing on given point.
Uses old values of up as hint whenever possible.
Definition at line 38 of file camera.cc.
References crossProduct(), dotProduct(), forward, normalize(), origin, right, sub(), and up.
Referenced by doRedraw().
void Camera::setForward (double v[3])
Defines the forward vector used by the camera.
Must be orthogonal to right and up vectors.
Definition at line 36 of file camera.cc.
References assign(), forward, and normalize().
void Camera::setOrigin (double v[3])
Definition at line 33 of file camera.cc.
References assign(), and origin.
Referenced by doRedraw().
void Camera::setRight (double v[3])
Defines the right vector used by the camera.
Must be orthogonal to up and forward vectors.
Definition at line 35 of file camera.cc.
References assign(), normalize(), and right.
void Camera::setUp (double v[3])
Defines the up vector used by the camera, usually set to +Y.
Must be orthogonal to right and forward vectors.
Definition at line 34 of file camera.cc.
References assign(), normalize(), and up.
Referenced by doRedraw().
Member Data Documentation
double Camera::forward[3] private
Definition at line 63 of file camera.h.
Referenced by Camera(), getPixelRay(), setFocus(), and setForward().
double Camera::origin[3] private
Definition at line 59 of file camera.h.
Referenced by Camera(), setFocus(), and setOrigin().
double Camera::right[3] private
Definition at line 62 of file camera.h.
Referenced by Camera(), getPixelRay(), setFocus(), and setRight().
double Camera::tanFovX private
Definition at line 65 of file camera.h.
Referenced by Camera(), and getPixelRay().
double Camera::tanFovY private
Definition at line 65 of file camera.h.
Referenced by Camera(), and getPixelRay().
double Camera::up[3] private
Definition at line 61 of file camera.h.
Referenced by Camera(), getPixelRay(), setFocus(), and setUp().
The documentation for this class was generated from the following files:
camera.h
camera.cc