Tracy: Sphere Class Reference
Sphere Class Reference
A sphere of given radius.
#include <sphere.h>
Public Member Functions
Sphere (double radius)
~Sphere ()
double lineTest (double origin[3], double direction[3], double maxDistance)
Must do the line intersection test and return the closest distance in which a ray originating in origin with given direction intersects the object - if such a point exists closer than maxDistance.
void getNormal (double point[3], double normal[3])
Compute the normal of the object at the given point.
bool isInside (double point[3])
Tests if a point is inside the object or not.
Public Member Functions inherited from Object
Object ()
virtual ~Object ()=0
All objects must have a virtual destructor so that they can be deallocated properly and to dereference any contained objects.
virtual void setMaterial (Material *material)
Sets up a default material to use for this object.
virtual void getLightingProperties (double point[3], LightingProperties *props, double normal[3])
Default material handling that queries the default material given for this object.
Public Member Functions inherited from Material
Material ()
Public Member Functions inherited from ReferencedObject
ReferencedObject ()
virtual ~ReferencedObject ()
void reference ()
Call when an object reference is added to memory.
void dereference ()
Call when an object is dereferenced.
Private Attributes
double radius
Additional Inherited Members
Protected Attributes inherited from Object
Material * material
Material used by the default getLightingProperties function.
Detailed Description
A sphere of given radius.
Definition at line 33 of file sphere.h.
Constructor & Destructor Documentation
Sphere::Sphere (double radius)
Definition at line 27 of file sphere.cc.
References radius.
Sphere::~Sphere ()
Definition at line 30 of file sphere.cc.
Member Function Documentation
void Sphere::getNormal (double point[3], double normal[3]) virtual
Compute the normal of the object at the given point.
Result is not guaranteed to be of unit length.
Implements Object.
Definition at line 49 of file sphere.cc.
References assign().
bool Sphere::isInside (double point[3]) virtual
Tests if a point is inside the object or not.
Implements Object.
Definition at line 53 of file sphere.cc.
References dotProduct(), and radius.
double Sphere::lineTest (double origin[3], double direction[3], double maxDistance) virtual
Must do the line intersection test and return the closest distance in which a ray originating in origin with given direction intersects the object - if such a point exists closer than maxDistance.
Returns distance MAX_DISTANCE if no such intersection exists.
Direction is not neccessarily a vector of unit length, and distances are measured in multiples of this vector.
Implements Object.
Definition at line 32 of file sphere.cc.
References dotProduct(), MAX_DISTANCE, and radius.
Member Data Documentation
double Sphere::radius private
Definition at line 43 of file sphere.h.
Referenced by isInside(), lineTest(), and Sphere().
The documentation for this class was generated from the following files:
sphere.h
sphere.cc