Tracy: Transform Class Reference
Transform Class Reference
Represents generic affine transformations.
#include <transform.h>
Public Member Functions
Transform (Object *child)
~Transform ()
double lineTest (double origin[3], double direction[3], double maxDistance)
Must do the line intersection test and return the closest distance in which a ray originating in origin with given direction intersects the object - if such a point exists closer than maxDistance.
void getNormal (double point[3], double normal[3])
Compute the normal of the object at the given point.
bool isInside (double point[3])
Tests if a point is inside the object or not.
void identity ()
Resets the transform to the identity matrix.
void translate (double dx, double dy, double dz)
Performs a translation.
void scale (double sx, double sy, double sz)
Performs a scale.
void rotateX (double rad)
Rotates around X-axis.
void rotateY (double rad)
Rotates around Y-axis.
void rotateZ (double rad)
Rotates around Z-axis.
virtual void getLightingProperties (double point[3], LightingProperties *props, double normal[3])
Default material handling that queries the default material given for this object.
Public Member Functions inherited from Object
Object ()
virtual ~Object ()=0
All objects must have a virtual destructor so that they can be deallocated properly and to dereference any contained objects.
virtual void setMaterial (Material *material)
Sets up a default material to use for this object.
Public Member Functions inherited from Material
Material ()
Public Member Functions inherited from ReferencedObject
ReferencedObject ()
virtual ~ReferencedObject ()
void reference ()
Call when an object reference is added to memory.
void dereference ()
Call when an object is dereferenced.
Private Member Functions
void computeInverseTransform ()
Private Attributes
Matrix4d forward
Matrix4d inverse
Object * child
Additional Inherited Members
Protected Attributes inherited from Object
Material * material
Material used by the default getLightingProperties function.
Detailed Description
Represents generic affine transformations.
Can contain a single child object and performs a transformation on it's position and shape.
Definition at line 35 of file transform.h.
Constructor & Destructor Documentation
Transform::Transform (Object * child)
Definition at line 27 of file transform.cc.
References child, forward, identityMatrix(), inverse, and ReferencedObject::reference().
Transform::~Transform ()
Definition at line 33 of file transform.cc.
References child, and ReferencedObject::dereference().
Member Function Documentation
void Transform::computeInverseTransform () private
Definition at line 121 of file transform.cc.
References forward, and inverse.
Referenced by rotateX(), rotateY(), rotateZ(), scale(), and translate().
void Transform::getLightingProperties (double point[3], LightingProperties * props, double normal[3]) virtual
Default material handling that queries the default material given for this object.
Reimplemented from Object.
Definition at line 159 of file transform.cc.
References child, Material::getLightingProperties(), Object::getLightingProperties(), inverse, and Object::material.
void Transform::getNormal (double point[3], double normal[3]) virtual
Compute the normal of the object at the given point.
Result is not guaranteed to be of unit length.
Implements Object.
Definition at line 57 of file transform.cc.
References assign(), child, forward, Object::getNormal(), and inverse.
void Transform::identity ()
Resets the transform to the identity matrix.
Definition at line 81 of file transform.cc.
References forward, identityMatrix(), and inverse.
Referenced by doRedraw().
bool Transform::isInside (double point[3]) virtual
Tests if a point is inside the object or not.
Implements Object.
Definition at line 71 of file transform.cc.
References child, inverse, and Object::isInside().
double Transform::lineTest (double origin[3], double direction[3], double maxDistance) virtual
Must do the line intersection test and return the closest distance in which a ray originating in origin with given direction intersects the object - if such a point exists closer than maxDistance.
Returns distance MAX_DISTANCE if no such intersection exists.
Direction is not neccessarily a vector of unit length, and distances are measured in multiples of this vector.
Implements Object.
Definition at line 36 of file transform.cc.
References child, inverse, and Object::lineTest().
void Transform::rotateX (double rad)
Rotates around X-axis.
Definition at line 107 of file transform.cc.
References computeInverseTransform(), forward, and rotateMatrixX().
Referenced by doRedraw().
void Transform::rotateY (double rad)
Rotates around Y-axis.
Definition at line 111 of file transform.cc.
References computeInverseTransform(), forward, and rotateMatrixY().
void Transform::rotateZ (double rad)
Rotates around Z-axis.
Definition at line 115 of file transform.cc.
References computeInverseTransform(), forward, and rotateMatrixZ().
void Transform::scale (double sx, double sy, double sz)
Performs a scale.
Definition at line 97 of file transform.cc.
References assign(), computeInverseTransform(), forward, identityMatrix(), and matrixMult().
Referenced by doRedraw().
void Transform::translate (double dx, double dy, double dz)
Performs a translation.
Definition at line 86 of file transform.cc.
References assign(), computeInverseTransform(), forward, identityMatrix(), and matrixMult().
Referenced by doRedraw().
Member Data Documentation
Object* Transform::child private
Definition at line 68 of file transform.h.
Referenced by getLightingProperties(), getNormal(), isInside(), lineTest(), Transform(), and ~Transform().
Matrix4d Transform::forward private
Definition at line 66 of file transform.h.
Referenced by computeInverseTransform(), getNormal(), identity(), rotateX(), rotateY(), rotateZ(), scale(), Transform(), and translate().
Matrix4d Transform::inverse private
Definition at line 67 of file transform.h.
Referenced by computeInverseTransform(), getLightingProperties(), getNormal(), identity(), isInside(), lineTest(), and Transform().
The documentation for this class was generated from the following files:
transform.h
transform.cc