Tracy: Object Class Reference
Object Class Reference abstract
Abstract base class for all renderable objects.
#include <object.h>
Public Member Functions
Object ()
virtual ~Object ()=0
All objects must have a virtual destructor so that they can be deallocated properly and to dereference any contained objects.
virtual double lineTest (double origin[3], double direction[3], double maxDistance)=0
Must do the line intersection test and return the closest distance in which a ray originating in origin with given direction intersects the object - if such a point exists closer than maxDistance.
virtual void getNormal (double point[3], double normal[3])=0
Compute the normal of the object at the given point.
virtual bool isInside (double point[3])=0
Tests if a point is inside the object or not.
virtual void setMaterial (Material *material)
Sets up a default material to use for this object.
virtual void getLightingProperties (double point[3], LightingProperties *props, double normal[3])
Default material handling that queries the default material given for this object.
Public Member Functions inherited from Material
Material ()
Public Member Functions inherited from ReferencedObject
ReferencedObject ()
virtual ~ReferencedObject ()
void reference ()
Call when an object reference is added to memory.
void dereference ()
Call when an object is dereferenced.
Protected Attributes
Material * material
Material used by the default getLightingProperties function.
Detailed Description
Abstract base class for all renderable objects.
Each concrete instance of this class must contain virtual functions that are used to perform line tests, computing normals and lighting properties.
Definition at line 39 of file object.h.
Constructor & Destructor Documentation
Object::Object ()
Definition at line 29 of file object.cc.
References material.
Object::~Object () pure virtual
All objects must have a virtual destructor so that they can be deallocated properly and to dereference any contained objects.
Definition at line 30 of file object.cc.
References ReferencedObject::dereference(), and material.
Member Function Documentation
void Object::getLightingProperties (double point[3], LightingProperties * props, double normal[3]) virtual
Default material handling that queries the default material given for this object.
Implements Material.
Reimplemented in Inverse, Transform, and Intersection.
Definition at line 36 of file object.cc.
References Material::getLightingProperties(), and material.
Referenced by Transform::getLightingProperties(), and Raytracer::raytrace().
virtual void Object::getNormal (double point[3], double normal[3]) pure virtual
Compute the normal of the object at the given point.
Result is not guaranteed to be of unit length.
Implemented in Inverse, Intersection, Transform, Sphere, and Plane.
Referenced by Transform::getNormal(), and Raytracer::raytrace().
virtual bool Object::isInside (double point[3]) pure virtual
Tests if a point is inside the object or not.
Implemented in Inverse, Intersection, Transform, Sphere, and Plane.
Referenced by Transform::isInside().
virtual double Object::lineTest (double origin[3], double direction[3], double maxDistance) pure virtual
Must do the line intersection test and return the closest distance in which a ray originating in origin with given direction intersects the object - if such a point exists closer than maxDistance.
Returns distance MAX_DISTANCE if no such intersection exists.
Direction is not neccessarily a vector of unit length, and distances are measured in multiples of this vector.
Implemented in Inverse, Intersection, Transform, Sphere, and Plane.
Referenced by Transform::lineTest(), and Raytracer::raytrace().
void Object::setMaterial (Material * material) virtual
Sets up a default material to use for this object.
Definition at line 31 of file object.cc.
References ReferencedObject::dereference(), material, and ReferencedObject::reference().
Referenced by main().
Member Data Documentation
Material* Object::material protected
Material used by the default getLightingProperties function.
Definition at line 71 of file object.h.
Referenced by Transform::getLightingProperties(), getLightingProperties(), Object(), setMaterial(), and ~Object().
The documentation for this class was generated from the following files:
object.h
object.cc