Tracy: Plane Class Reference
Plane Class Reference
An infinite plane with given normal and offset from origo.
#include <plane.h>
Public Member Functions
Plane (double normal[3], double offset)
~Plane ()
double lineTest (double origin[3], double direction[3], double maxDistance)
Must do the line intersection test and return the closest distance in which a ray originating in origin with given direction intersects the object - if such a point exists closer than maxDistance.
void getNormal (double point[3], double normal[3])
Compute the normal of the object at the given point.
bool isInside (double point[3])
Tests if a point is inside the object or not.
Public Member Functions inherited from Object
Object ()
virtual ~Object ()=0
All objects must have a virtual destructor so that they can be deallocated properly and to dereference any contained objects.
virtual void setMaterial (Material *material)
Sets up a default material to use for this object.
virtual void getLightingProperties (double point[3], LightingProperties *props, double normal[3])
Default material handling that queries the default material given for this object.
Public Member Functions inherited from Material
Material ()
Public Member Functions inherited from ReferencedObject
ReferencedObject ()
virtual ~ReferencedObject ()
void reference ()
Call when an object reference is added to memory.
void dereference ()
Call when an object is dereferenced.
Private Attributes
double normal [3]
double offset
Additional Inherited Members
Protected Attributes inherited from Object
Material * material
Material used by the default getLightingProperties function.
Detailed Description
An infinite plane with given normal and offset from origo.
Definition at line 32 of file plane.h.
Constructor & Destructor Documentation
Plane::Plane (double normal[3], double offset)
Definition at line 27 of file plane.cc.
References assign(), and offset.
Plane::~Plane ()
Definition at line 31 of file plane.cc.
Member Function Documentation
void Plane::getNormal (double point[3], double normal[3]) virtual
Compute the normal of the object at the given point.
Result is not guaranteed to be of unit length.
Implements Object.
Definition at line 48 of file plane.cc.
References assign().
bool Plane::isInside (double point[3]) virtual
Tests if a point is inside the object or not.
Implements Object.
Definition at line 52 of file plane.cc.
References dotProduct(), normal, and offset.
double Plane::lineTest (double origin[3], double direction[3], double maxDistance) virtual
Must do the line intersection test and return the closest distance in which a ray originating in origin with given direction intersects the object - if such a point exists closer than maxDistance.
Returns distance MAX_DISTANCE if no such intersection exists.
Direction is not neccessarily a vector of unit length, and distances are measured in multiples of this vector.
Implements Object.
Definition at line 33 of file plane.cc.
References debugThisPixel, dotProduct(), MAX_DISTANCE, normal, offset, and printDebugIndentation().
Member Data Documentation
double Plane::normal[3] private
Definition at line 42 of file plane.h.
Referenced by isInside(), and lineTest().
double Plane::offset private
Definition at line 42 of file plane.h.
Referenced by isInside(), lineTest(), and Plane().
The documentation for this class was generated from the following files:
plane.h
plane.cc