Tracy: Raytracer Class Reference
Raytracer Class Reference
Main class for performing all raytracing operations.
#include <raytracer.h>
Public Member Functions
Raytracer ()
~Raytracer ()
void setBackground (double[3])
Sets the background colour of the scene, ie.
void setAmbientLight (double[3])
Sets the global ambient light in the scene.
void addLight (Light *)
Adds a lightsource to the scene.
void addObject (Object *)
Adds an object to the scene.
void setCamera (Camera *)
Sets the camera object to be used when determining origin of the rays.
Camera * getCamera ()
Gives the camera object currently used.
void raytrace (double origin[3], double direction[3], double rgb[3], double contribution)
Basic raytracing routine that computes a colour to assign to a ray originating in origin with the given direction.
void raytrace (int x, int y, double rgb[3])
Special case of general raytracing routine for screen pixel X,Y.
Private Attributes
Camera * camera
double background [3]
double ambientLight [3]
class std::set< Light * > * lights
class std::set< Object * > * objects
Detailed Description
Main class for performing all raytracing operations.
To use, instantiate this class and give it a scene graph using the addObject and addLight operations. Also pass it a camera object using the setCamera function and give global lighting properties using setBackground nad setAmbientLight.
Once ready to use, the actual raytracing operation can be performed by calling the raytracer function for every pixel on the screen.
Note that all objects are asssumed to be reentrant during the raytracring (ie. they should not change any internal state variables), and that updates on them should only be made in between frames.
Definition at line 56 of file raytracer.h.
Constructor & Destructor Documentation
Raytracer::Raytracer ()
Definition at line 31 of file raytracer.cc.
References zero().
Referenced by main().
Raytracer::~Raytracer ()
Definition at line 37 of file raytracer.cc.
Member Function Documentation
void Raytracer::addLight (Light * light)
Adds a lightsource to the scene.
Definition at line 58 of file raytracer.cc.
References ReferencedObject::reference().
Referenced by main().
void Raytracer::addObject (Object * object)
Adds an object to the scene.
Definition at line 54 of file raytracer.cc.
Referenced by main().
Camera * Raytracer::getCamera ()
Gives the camera object currently used.
Definition at line 63 of file raytracer.cc.
Referenced by doRedraw().
void Raytracer::raytrace (double origin[3], double direction[3], double rgb[3], double contribution)
Basic raytracing routine that computes a colour to assign to a ray originating in origin with the given direction.
If no intersecting objects are found then it assigns the background colour to the vector rgb, otherwise the result of doing the light computations and recursive raytracing from the intersection point.
Contribution is a hint for how much the resuling colours will contribute to the screen pixels and can be used to limit recursion.
Definition at line 69 of file raytracer.cc.
References LightingProperties::ambient, Light::colour, debugIndentation, debugThisPixel, LightingProperties::diffuse, dotProduct(), Object::getLightingProperties(), Object::getNormal(), length(), Object::lineTest(), MAX_DISTANCE, normalize(), Light::position, printDebugIndentation(), LightingProperties::reflection, LightingProperties::shininess, LightingProperties::specular, and sub().
Referenced by doRedraw().
void Raytracer::raytrace (int x, int y, double rgb[3])
Special case of general raytracing routine for screen pixel X,Y.
Fetches the origin/direction from the current camera settings.
Definition at line 64 of file raytracer.cc.
References screenHeight, and screenWidth.
void Raytracer::setAmbientLight (double col[3])
Sets the global ambient light in the scene.
Definition at line 52 of file raytracer.cc.
References assign().
Referenced by main().
void Raytracer::setBackground (double col[3])
Sets the background colour of the scene, ie.
the colour used for all pixels that hit no object.
Definition at line 51 of file raytracer.cc.
References assign().
void Raytracer::setCamera (Camera * cam)
Sets the camera object to be used when determining origin of the rays.
Definition at line 62 of file raytracer.cc.
Referenced by main().
Member Data Documentation
double Raytracer::ambientLight[3] private
Definition at line 95 of file raytracer.h.
Referenced by main().
double Raytracer::background[3] private
Definition at line 94 of file raytracer.h.
Camera* Raytracer::camera private
Definition at line 93 of file raytracer.h.
Referenced by doRedraw().
class std::set< Light * >* Raytracer::lights private
Definition at line 97 of file raytracer.h.
class std::set< Object * >* Raytracer::objects private
Definition at line 98 of file raytracer.h.
The documentation for this class was generated from the following files:
raytracer.h
raytracer.cc