Tracy: Intersection Class Reference
Intersection Class Reference
Creates new objects as the intersection of multiple child objects.
#include <csg.h>
Public Member Functions
Intersection ()
~Intersection ()
void addObject (Object *)
double lineTest (double origin[3], double direction[3], double maxDistance)
Must do the line intersection test and return the closest distance in which a ray originating in origin with given direction intersects the object - if such a point exists closer than maxDistance.
void getNormal (double point[3], double normal[3])
Compute the normal of the object at the given point.
bool isInside (double point[3])
Tests if a point is inside the object or not.
void getLightingProperties (double point[3], LightingProperties *props, double normal[3])
Default material handling that queries the default material given for this object.
Public Member Functions inherited from Object
Object ()
virtual ~Object ()=0
All objects must have a virtual destructor so that they can be deallocated properly and to dereference any contained objects.
virtual void setMaterial (Material *material)
Sets up a default material to use for this object.
Public Member Functions inherited from Material
Material ()
Public Member Functions inherited from ReferencedObject
ReferencedObject ()
virtual ~ReferencedObject ()
void reference ()
Call when an object reference is added to memory.
void dereference ()
Call when an object is dereferenced.
Private Attributes
class std::set< Object * > * objects
Object * lastObject [MAX_OMP_THREADS]
Additional Inherited Members
Protected Attributes inherited from Object
Material * material
Material used by the default getLightingProperties function.
Detailed Description
Creates new objects as the intersection of multiple child objects.
This is one of the basic CSG building blocks of more complex geometry. In this current implementation it is done in a generic, but inefficeint manner. More efficient code can be made using harder restrictions on the contained child objects.
Definition at line 38 of file csg.h.
Constructor & Destructor Documentation
Intersection::Intersection ()
Definition at line 30 of file csg.cc.
References MAX_OMP_THREADS.
Intersection::~Intersection ()
Definition at line 34 of file csg.cc.
Member Function Documentation
void Intersection::addObject (Object * object)
Definition at line 42 of file csg.cc.
Referenced by main().
void Intersection::getLightingProperties (double point[3], LightingProperties * props, double normal[3]) virtual
Default material handling that queries the default material given for this object.
Reimplemented from Object.
Definition at line 137 of file csg.cc.
void Intersection::getNormal (double point[3], double normal[3]) virtual
Compute the normal of the object at the given point.
Result is not guaranteed to be of unit length.
Implements Object.
Definition at line 114 of file csg.cc.
bool Intersection::isInside (double point[3]) virtual
Tests if a point is inside the object or not.
Implements Object.
Definition at line 125 of file csg.cc.
double Intersection::lineTest (double origin[3], double direction[3], double maxDistance) virtual
Must do the line intersection test and return the closest distance in which a ray originating in origin with given direction intersects the object - if such a point exists closer than maxDistance.
Returns distance MAX_DISTANCE if no such intersection exists.
Direction is not neccessarily a vector of unit length, and distances are measured in multiples of this vector.
Implements Object.
Definition at line 47 of file csg.cc.
References assign(), debugIndentation, debugThisPixel, MAX_DISTANCE, and printDebugIndentation().
Member Data Documentation
Object* Intersection::lastObject[MAX_OMP_THREADS] private
Definition at line 53 of file csg.h.
class std::set< Object * >* Intersection::objects private
Definition at line 51 of file csg.h.
The documentation for this class was generated from the following files:
csg.h
csg.cc