Tracy: main.cc File Reference
main.cc File Reference
The main entry point and code skeleton for a raytracer.
#include "general.h"
#include "camera.h"
#include "raytracer.h"
#include "sphere.h"
#include "plane.h"
#include "light.h"
#include "transform.h"
#include "noise.h"
#include "csg.h"
Functions
void doRedraw ()
void doKeyboard (int, int, int)
void tick (double)
void * renderingThread (void *arg)
void renderPixels (int offset, int skip)
int main (int argc, char **args)
void putPixel (int x, int y, int r, int g, int b)
void printDebugIndentation ()
Variables
int screenWidth
int screenHeight
int isRunning
double gTime
double simulationSpeed =5.0
SDL_Surface * screen
double cameraOrbit [2] ={0.0,0.0}
Raytracer * raytracer
Transform * object1
Transform * object2
int debugPixelX =-1
Used for debugging, note that we drop down to singel threaded mode when we are using this per-pixel debugging.
int debugPixelY
int debugThisPixel =0
int debugIndentation =0
Detailed Description
The main entry point and code skeleton for a raytracer.
Definition in file main.cc.
Function Documentation
void doKeyboard (int key, int mouseX, int mouseY)
Definition at line 213 of file main.cc.
Referenced by main().
void doRedraw ()
Definition at line 224 of file main.cc.
References Raytracer::camera, cameraOrbit, debugPixelX, debugPixelY, debugThisPixel, Raytracer::getCamera(), gTime, Transform::identity(), M_PI, putPixel(), Raytracer::raytrace(), Transform::rotateX(), Transform::scale(), screenHeight, screenWidth, Camera::setFocus(), Camera::setOrigin(), Camera::setUp(), Transform::translate(), and zero().
Referenced by main().
int main (int argc, char ** args)
Definition at line 86 of file main.cc.
References MaterialMap::add(), Raytracer::addLight(), Intersection::addObject(), Raytracer::addObject(), Raytracer::ambientLight, debugPixelX, debugPixelY, doKeyboard(), doRedraw(), initNoise(), isRunning, MaterialMap::Noise, Raytracer::Raytracer(), raytracer, screen, screenHeight, screenWidth, Raytracer::setAmbientLight(), Raytracer::setCamera(), Object::setMaterial(), and tick().
void printDebugIndentation ()
Definition at line 291 of file main.cc.
References debugIndentation.
Referenced by Plane::lineTest(), Intersection::lineTest(), and Raytracer::raytrace().
void putPixel (int x, int y, int r, int g, int b)
Definition at line 217 of file main.cc.
References screen.
Referenced by doRedraw().
void* renderingThread (void * arg)
void renderPixels (int offset, int skip)
void tick (double dt)
Definition at line 292 of file main.cc.
References cameraOrbit, and gTime.
Referenced by main().
Variable Documentation
double cameraOrbit[2] ={0.0,0.0}
Definition at line 74 of file main.cc.
Referenced by doRedraw(), and tick().
int debugIndentation =0
Definition at line 84 of file main.cc.
Referenced by Intersection::lineTest(), printDebugIndentation(), and Raytracer::raytrace().
int debugPixelX =-1
Used for debugging, note that we drop down to singel threaded mode when we are using this per-pixel debugging.
Thus any threading related bugs will NOT be visible using this method.
Definition at line 83 of file main.cc.
Referenced by doRedraw(), and main().
int debugPixelY
Definition at line 83 of file main.cc.
Referenced by doRedraw(), and main().
int debugThisPixel =0
Definition at line 83 of file main.cc.
Referenced by doRedraw(), Plane::lineTest(), Intersection::lineTest(), and Raytracer::raytrace().
double gTime
Definition at line 71 of file main.cc.
Referenced by doRedraw(), and tick().
int isRunning
Definition at line 70 of file main.cc.
Referenced by main().
Transform* object1
Definition at line 77 of file main.cc.
Transform * object2
Definition at line 77 of file main.cc.
Raytracer* raytracer
Definition at line 76 of file main.cc.
Referenced by main().
SDL_Surface* screen
Definition at line 72 of file main.cc.
Referenced by main(), and putPixel().
int screenHeight
Definition at line 70 of file main.cc.
Referenced by doRedraw(), main(), and Raytracer::raytrace().
int screenWidth
Definition at line 70 of file main.cc.
Referenced by doRedraw(), main(), and Raytracer::raytrace().
double simulationSpeed =5.0
Definition at line 71 of file main.cc.