Tracy: noise.cc File Reference
noise.cc File Reference
Implements functions for computing semi-random noise in 2-5 dimensions.
#include "noise.h"
#include "stdlib.h"
Functions
void initNoise ()
double semiRand (int x)
double semiRand (int x, int y)
double semiRand (int x, int y, int z)
double semiRand (int x, int y, int z, int w)
double semiRand (int x, int y, int z, int w, int h)
double noise (double a)
double noise (double a, double b)
double noise (double a, double b, double c)
double noise (double a, double b, double c, double d)
Variables
int randData [5][1024]
Detailed Description
Implements functions for computing semi-random noise in 2-5 dimensions.
Definition in file noise.cc.
Function Documentation
void initNoise ()
Definition at line 30 of file noise.cc.
References randData.
Referenced by main().
double noise (double a)
Definition at line 52 of file noise.cc.
References semiRand().
Referenced by NoiseMaterial::getLightingProperties(), and MaterialMap::getLightingProperties().
double noise (double a, double b)
Definition at line 59 of file noise.cc.
References semiRand().
double noise (double a, double b, double c)
Definition at line 69 of file noise.cc.
References semiRand().
double noise (double a, double b, double c, double d)
Definition at line 84 of file noise.cc.
References semiRand().
double semiRand (int x) inline
Definition at line 36 of file noise.cc.
References randData.
Referenced by noise().
double semiRand (int x, int y) inline
Definition at line 39 of file noise.cc.
References randData.
double semiRand (int x, int y, int z) inline
Definition at line 42 of file noise.cc.
References randData.
double semiRand (int x, int y, int z, int w) inline
Definition at line 45 of file noise.cc.
References randData.
double semiRand (int x, int y, int z, int w, int h) inline
Definition at line 48 of file noise.cc.
References randData.
Variable Documentation
int randData[5][1024]
Definition at line 28 of file noise.cc.
Referenced by initNoise(), and semiRand().