Tracy: noise.h File Reference
noise.h File Reference
Declares functions for computing semi-random noise in 2-5 dimensions.
Functions
void initNoise ()
double noise (double a)
double noise (double a, double b)
double noise (double a, double b, double c)
double noise (double a, double b, double c, double d)
Detailed Description
Declares functions for computing semi-random noise in 2-5 dimensions.
Definition in file noise.h.
Function Documentation
void initNoise ()
Definition at line 30 of file noise.cc.
References randData.
Referenced by main().
double noise (double a)
Definition at line 52 of file noise.cc.
References semiRand().
Referenced by NoiseMaterial::getLightingProperties(), and MaterialMap::getLightingProperties().
double noise (double a, double b)
Definition at line 59 of file noise.cc.
References semiRand().
double noise (double a, double b, double c)
Definition at line 69 of file noise.cc.
References semiRand().
double noise (double a, double b, double c, double d)
Definition at line 84 of file noise.cc.
References semiRand().