Tracy: vector.h File Reference
vector.h File Reference
Declares some miscellaneous.
Typedefs
typedef double Matrix4d [4][4]
typedef double Matrix3d [3][3]
Functions
void assign (const float A[3], float C[3])
void assign (const double A[3], double C[3])
void crossProduct (const double A[3], const double B[3], double C[3])
double dotProduct (const double A[3], const double B[3])
void add (const double A[3], const double B[3], double C[3])
void sub (const double A[3], const double B[3], double C[3])
void normalize (double[3])
double length (double[3])
void zero (double[3])
void debugMatrix (Matrix4d)
Print out a matrix in a human readable form.
void homogenise (double A[4], double C[3])
Homogeneis A and assign to C.
void useMatrix (Matrix4d M, const double A[4], double C[4])
Assign to C the value M * A.
void useMatrix (Matrix3d, const double A[3], double C[3])
Assign to C the value M * A.
void useMatrix (Matrix4d A, const double x, const double y, const double z, double C[3])
Assign to C the value M * <x,y,z>
void useMatrix (Matrix4d A, const double x, const double y, const double z, float C[3])
Assign to C the value M * <x,y,z>
void identityMatrix (Matrix4d)
void assign (const Matrix4d A, Matrix4d C)
void matrixMult (Matrix4d A, Matrix4d B, Matrix4d C)
void rotateMatrixX (double, Matrix4d)
void rotateMatrixY (double, Matrix4d)
void rotateMatrixZ (double, Matrix4d)
void translateXYZ (double x, double y, double z, Matrix4d)
Detailed Description
Declares some miscellaneous.
math vector/matrix operations.
Definition in file vector.h.
Typedef Documentation
typedef double Matrix3d[3][3]
Definition at line 38 of file vector.h.
typedef double Matrix4d[4][4]
Definition at line 37 of file vector.h.
Function Documentation
void add (const double A[3], const double B[3], double C[3])
Definition at line 33 of file vector.cc.
void assign (const float A[3], float C[3])
Definition at line 149 of file vector.cc.
void assign (const double A[3], double C[3])
Definition at line 146 of file vector.cc.
void assign (const Matrix4d A, Matrix4d C)
Definition at line 138 of file vector.cc.
Referenced by Plane::getNormal(), Sphere::getNormal(), Transform::getNormal(), Camera::getPixelRay(), Light::Light(), Intersection::lineTest(), Plane::Plane(), rotateMatrixX(), rotateMatrixY(), rotateMatrixZ(), Transform::scale(), Raytracer::setAmbientLight(), Raytracer::setBackground(), Camera::setForward(), Camera::setOrigin(), Camera::setRight(), Camera::setUp(), Transform::translate(), and translateXYZ().
void crossProduct (const double A[3], const double B[3], double C[3])
Definition at line 51 of file vector.cc.
Referenced by Camera::setFocus().
void debugMatrix (Matrix4d)
Print out a matrix in a human readable form.
Definition at line 66 of file vector.cc.
double dotProduct (const double A[3], const double B[3])
Definition at line 58 of file vector.cc.
Referenced by Plane::isInside(), Sphere::isInside(), Plane::lineTest(), Sphere::lineTest(), Raytracer::raytrace(), and Camera::setFocus().
void homogenise (double A[4], double C[3])
Homogeneis A and assign to C.
Definition at line 84 of file vector.cc.
void identityMatrix (Matrix4d)
Definition at line 151 of file vector.cc.
Referenced by Transform::identity(), Transform::scale(), Transform::Transform(), and Transform::translate().
double length (double [3])
Definition at line 47 of file vector.cc.
Referenced by Raytracer::raytrace().
void matrixMult (Matrix4d A, Matrix4d B, Matrix4d C)
Definition at line 74 of file vector.cc.
Referenced by rotateMatrixX(), rotateMatrixY(), rotateMatrixZ(), Transform::scale(), Transform::translate(), and translateXYZ().
void normalize (double [3])
Definition at line 42 of file vector.cc.
Referenced by Camera::getPixelRay(), Raytracer::raytrace(), Camera::setFocus(), Camera::setForward(), Camera::setRight(), and Camera::setUp().
void rotateMatrixX (double , Matrix4d)
Definition at line 158 of file vector.cc.
References assign(), and matrixMult().
Referenced by Transform::rotateX().
void rotateMatrixY (double , Matrix4d)
Definition at line 168 of file vector.cc.
References assign(), and matrixMult().
Referenced by Transform::rotateY().
void rotateMatrixZ (double , Matrix4d)
Definition at line 178 of file vector.cc.
References assign(), and matrixMult().
Referenced by Transform::rotateZ().
void sub (const double A[3], const double B[3], double C[3])
Definition at line 38 of file vector.cc.
Referenced by Raytracer::raytrace(), and Camera::setFocus().
void translateXYZ (double x, double y, double z, Matrix4d)
Definition at line 188 of file vector.cc.
References assign(), and matrixMult().
void useMatrix (Matrix4d M, const double A[4], double C[4])
Assign to C the value M * A.
Definition at line 91 of file vector.cc.
void useMatrix (Matrix3d , const double A[3], double C[3])
Assign to C the value M * A.
Definition at line 102 of file vector.cc.
void useMatrix (Matrix4d A, const double x, const double y, const double z, double C[3])
Assign to C the value M * <x,y,z>
Definition at line 114 of file vector.cc.
void useMatrix (Matrix4d A, const double x, const double y, const double z, float C[3])
Assign to C the value M * <x,y,z>
Definition at line 126 of file vector.cc.
void zero (double [3])
Definition at line 199 of file vector.cc.
Referenced by Camera::Camera(), doRedraw(), NoiseMaterial::getLightingProperties(), MaterialMap::getLightingProperties(), and Raytracer::Raytracer().