Tracy: vector.cc File Reference
vector.cc File Reference
Implements some miscellaneous.
#include <stdio.h>
#include <math.h>
#include "general.h"
#include "vector.h"
Functions
void add (const double A[3], const double B[3], double C[3])
void sub (const double A[3], const double B[3], double C[3])
void normalize (double C[3])
double length (double A[3])
void crossProduct (const double A[3], const double B[3], double C[3])
double dotProduct (const double A[3], const double B[3])
void debugMatrix (Matrix4d m)
Print out a matrix in a human readable form.
void matrixMult (Matrix4d A, Matrix4d B, Matrix4d C)
void homogenise (double A[4], double C[3])
Homogeneis A and assign to C.
void useMatrix (Matrix4d A, const double B[4], double C[4])
Assign to C the value M * A.
void useMatrix (Matrix3d A, const double B[3], double C[3])
Assign to C the value M * A.
void useMatrix (Matrix4d m, const double x, const double y, const double z, double C[3])
Assign to C the value M * <x,y,z>
void useMatrix (Matrix4d m, const double x, const double y, const double z, float C[3])
Assign to C the value M * <x,y,z>
void assign (const Matrix4d A, Matrix4d C)
void assign (const double A[3], double C[3])
void assign (const float A[3], float C[3])
void identityMatrix (Matrix4d m)
void rotateMatrixX (double v, Matrix4d m)
void rotateMatrixY (double v, Matrix4d m)
void rotateMatrixZ (double v, Matrix4d m)
void translateXYZ (double x, double y, double z, Matrix4d m)
void zero (double v[3])
Detailed Description
Implements some miscellaneous.
math vector/matrix operations.
Definition in file vector.cc.
Function Documentation
void add (const double A[3], const double B[3], double C[3])
Definition at line 33 of file vector.cc.
void assign (const Matrix4d A, Matrix4d C)
Definition at line 138 of file vector.cc.
Referenced by Plane::getNormal(), Sphere::getNormal(), Transform::getNormal(), Camera::getPixelRay(), Light::Light(), Intersection::lineTest(), Plane::Plane(), rotateMatrixX(), rotateMatrixY(), rotateMatrixZ(), Transform::scale(), Raytracer::setAmbientLight(), Raytracer::setBackground(), Camera::setForward(), Camera::setOrigin(), Camera::setRight(), Camera::setUp(), Transform::translate(), and translateXYZ().
void assign (const double A[3], double C[3])
Definition at line 146 of file vector.cc.
void assign (const float A[3], float C[3])
Definition at line 149 of file vector.cc.
void crossProduct (const double A[3], const double B[3], double C[3])
Definition at line 51 of file vector.cc.
Referenced by Camera::setFocus().
void debugMatrix (Matrix4d m)
Print out a matrix in a human readable form.
Definition at line 66 of file vector.cc.
double dotProduct (const double A[3], const double B[3])
Definition at line 58 of file vector.cc.
Referenced by Plane::isInside(), Sphere::isInside(), Plane::lineTest(), Sphere::lineTest(), Raytracer::raytrace(), and Camera::setFocus().
void homogenise (double A[4], double C[3])
Homogeneis A and assign to C.
Definition at line 84 of file vector.cc.
void identityMatrix (Matrix4d m)
Definition at line 151 of file vector.cc.
Referenced by Transform::identity(), Transform::scale(), Transform::Transform(), and Transform::translate().
double length (double A[3])
Definition at line 47 of file vector.cc.
Referenced by Raytracer::raytrace().
void matrixMult (Matrix4d A, Matrix4d B, Matrix4d C)
Definition at line 74 of file vector.cc.
Referenced by rotateMatrixX(), rotateMatrixY(), rotateMatrixZ(), Transform::scale(), Transform::translate(), and translateXYZ().
void normalize (double C[3])
Definition at line 42 of file vector.cc.
Referenced by Camera::getPixelRay(), Raytracer::raytrace(), Camera::setFocus(), Camera::setForward(), Camera::setRight(), and Camera::setUp().
void rotateMatrixX (double v, Matrix4d m)
Definition at line 158 of file vector.cc.
References assign(), and matrixMult().
Referenced by Transform::rotateX().
void rotateMatrixY (double v, Matrix4d m)
Definition at line 168 of file vector.cc.
References assign(), and matrixMult().
Referenced by Transform::rotateY().
void rotateMatrixZ (double v, Matrix4d m)
Definition at line 178 of file vector.cc.
References assign(), and matrixMult().
Referenced by Transform::rotateZ().
void sub (const double A[3], const double B[3], double C[3])
Definition at line 38 of file vector.cc.
Referenced by Raytracer::raytrace(), and Camera::setFocus().
void translateXYZ (double x, double y, double z, Matrix4d m)
Definition at line 188 of file vector.cc.
References assign(), and matrixMult().
void useMatrix (Matrix4d A, const double B[4], double C[4])
Assign to C the value M * A.
Definition at line 91 of file vector.cc.
void useMatrix (Matrix3d A, const double B[3], double C[3])
Assign to C the value M * A.
Definition at line 102 of file vector.cc.
void useMatrix (Matrix4d m, const double x, const double y, const double z, double C[3])
Assign to C the value M * <x,y,z>
Definition at line 114 of file vector.cc.
void useMatrix (Matrix4d m, const double x, const double y, const double z, float C[3])
Assign to C the value M * <x,y,z>
Definition at line 126 of file vector.cc.
void zero (double v[3])
Definition at line 199 of file vector.cc.
Referenced by Camera::Camera(), doRedraw(), NoiseMaterial::getLightingProperties(), MaterialMap::getLightingProperties(), and Raytracer::Raytracer().